# Generated by Django 4.2 on 2023-04-06 17:44

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True, verbose_name='Уникальный ключ в системе'),
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Уникальный ключ в системе')),
                ('point_from', models.CharField(max_length=64, verbose_name='Место отправления')),
                ('point_to', models.CharField(max_length=64, verbose_name='Место назначения')),
                ('distance', models.IntegerField(verbose_name='Расстояние')),
                ('speed', models.FloatField(verbose_name='Скорость')),
                ('start_date', models.DateTimeField(auto_now_add=True, verbose_name='Время начала поездки')),
                ('is_done', models.BooleanField(default=False, verbose_name='Поездка закончилась')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.vehicle', verbose_name='Транспортное средство')),
            ],
            options={
                'verbose_name': 'Поездка',
                'verbose_name_plural': 'Поездки',
            },
        ),
    ]
