# Generated by Django 4.2 on 2023-04-07 10:15

import api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_vehicle_id_trip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='distance',
            field=models.IntegerField(default=api.models.get_random_distance, verbose_name='Расстояние'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.vehicle', verbose_name='Транспортное средство'),
        ),
    ]
